from __future__ import annotations
import pathlib,re
from .util import atomic_write_json

FLOAT=r"[-+]?\d+(?:\.\d+)?"

def _first(pattern,text,flags=re.I|re.M):
    m=re.search(pattern,text,flags); return float(m.group(1)) if m else None

def parse_timing(text:str):
    # Parse explicit labeled values first; then common summary-table layouts.
    def lab(label):
        return _first(r"^\s*"+label+r"\s*\(ns\)\s*[:=]\s*("+FLOAT+r")", text, re.I|re.M)
    out={"wns_ns":lab("WNS"),"tns_ns":lab("TNS"),"whs_ns":lab("WHS"),"ths_ns":lab("THS")}
    # Common Vivado table: WNS(ns) TNS(ns) ... followed by numeric row.
    m=re.search(r"WNS\s*\(ns\).*?TNS\s*\(ns\).*?WHS\s*\(ns\).*?THS\s*\(ns\).*?\n\s*("+FLOAT+r")\s+("+FLOAT+r").*?\s+("+FLOAT+r")\s+("+FLOAT+r")", text, re.I|re.S)
    if m:
        vals=list(map(float,m.groups()))
        for k,v in zip(["wns_ns","tns_ns","whs_ns","ths_ns"],vals):
            if out[k] is None: out[k]=v
    uc=[
      _first(r"Unconstrained\s+Paths?\s*[:=]\s*(\d+)",text),
      _first(r"There are\s+(\d+)\s+unconstrained",text)
    ]
    out["unconstrained_paths"]=next((int(x) for x in uc if x is not None),None)
    low=text.lower()
    out["timing_met_phrase"]="timing constraints are met" in low or "all user specified timing constraints are met" in low
    out["timing_failed_phrase"]="timing constraints are not met" in low
    return out

def parse_util(text:str):
    res={}
    pats={
      "LUT":[r"Slice LUTs\s*\|\s*([\d,]+)\s*\|\s*([\d,]+)\s*\|\s*([\d.]+)",r"CLB LUTs\s*\|\s*([\d,]+).*?\|\s*([\d.]+)\s*\|"],
      "FF":[r"Slice Registers\s*\|\s*([\d,]+)\s*\|\s*([\d,]+)\s*\|\s*([\d.]+)",r"CLB Registers\s*\|\s*([\d,]+).*?\|\s*([\d.]+)\s*\|"],
      "BRAM":[r"Block RAM Tile\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)\s*\|\s*([\d.]+)"],
      "DSP":[r"DSPs\s*\|\s*([\d,]+)\s*\|\s*([\d,]+)\s*\|\s*([\d.]+)",r"DSP48E1 only\s*\|\s*([\d,]+).*?\|\s*([\d.]+)\s*\|"]
    }
    for k,arr in pats.items():
        for p in arr:
            m=re.search(p,text,re.I)
            if m:
                nums=[x.replace(",","") for x in m.groups()]
                try:
                    if len(nums)>=3: res[k]={"used":float(nums[0]),"available":float(nums[1]),"pct":float(nums[2])}
                    else: res[k]={"used":float(nums[0]),"pct":float(nums[-1])}
                except Exception: pass
                break
    return res

def scan_report(text:str,patterns:list[str]):
    hits=[]
    for pat in patterns:
        for m in re.finditer(re.escape(pat),text,re.I):
            line=text.count("\n",0,m.start())+1; hits.append({"pattern":pat,"line":line})
    return hits

def evaluate(timing:dict,util:dict,cfg:dict,report_hits:dict):
    reasons=[]; review=[]; tcfg=cfg.get("timing",{})
    checks=[("wns_ns",">=",tcfg.get("wns_min_ns",0.0)),("tns_ns","<=",tcfg.get("tns_max_ns",0.0)),("whs_ns",">=",tcfg.get("whs_min_ns",0.0)),("ths_ns","<=",tcfg.get("ths_max_ns",0.0))]
    for k,op,thr in checks:
        v=timing.get(k)
        if v is None: review.append(f"missing {k}")
        elif op==">=" and v<thr: reasons.append(f"{k}={v} < {thr}")
        elif op=="<=" and v>thr: reasons.append(f"{k}={v} > {thr}")
    up=timing.get("unconstrained_paths")
    if up is None: review.append("unconstrained path count not parsed")
    elif up>tcfg.get("unconstrained_paths_max",0): reasons.append(f"unconstrained_paths={up}")
    for r,lim in cfg.get("utilization_max_pct",{}).items():
        if r in util and util[r].get("pct",0)>lim: reasons.append(f"{r} utilization {util[r]['pct']}% > {lim}%")
    for name,hits in report_hits.items():
        if hits: reasons.append(f"{name}: {len(hits)} critical-pattern hits")
    status="FAIL" if reasons else ("REVIEW_REQUIRED" if review else "PASS")
    return {"status":status,"fail_reasons":reasons,"review_reasons":review,"timing":timing,"utilization":util,"report_hits":report_hits}

TCL_TEMPLATE=r'''# Auto-generated by native-ai-agent-guard
# Run after opening the desired synthesized/implemented design.
set outdir "{outdir}"
file mkdir $outdir
report_timing_summary -delay_type min_max -report_unconstrained -check_timing_verbose -file "$outdir/timing_summary.rpt"
report_methodology -file "$outdir/methodology.rpt"
report_drc -file "$outdir/drc.rpt"
report_clock_interaction -file "$outdir/clock_interaction.rpt"
catch {{ report_cdc -details -file "$outdir/cdc.rpt" }}
catch {{ report_utilization -file "$outdir/utilization.rpt" }}
catch {{ report_route_status -file "$outdir/route_status.rpt" }}
catch {{ report_high_fanout_nets -timing -load_types -max_nets 100 -file "$outdir/high_fanout.rpt" }}
catch {{ report_qor_suggestions -file "$outdir/qor_suggestions.rpt" }}
catch {{ check_timing -verbose > "$outdir/check_timing.rpt" }}
'''

def write_tcl(path:pathlib.Path,outdir:str):
    path.write_text(TCL_TEMPLATE.format(outdir=outdir.replace("\\","/")),encoding="utf-8")
